/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ConfiguredRouteRouteImport } from './routes/_configured/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfiguredLoginRouteImport } from './routes/_configured/login'
import { Route as ConfiguredAuthenticatedRouteRouteImport } from './routes/_configured/_authenticated/route'
import { Route as ConfiguredAuthenticatedTorrentsRouteImport } from './routes/_configured/_authenticated/torrents'
import { Route as ConfiguredAuthenticatedSettingsRouteImport } from './routes/_configured/_authenticated/settings'
import { Route as ConfiguredAuthenticatedAccountRouteImport } from './routes/_configured/_authenticated/account'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguredRouteRoute = ConfiguredRouteRouteImport.update({
  id: '/_configured',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguredLoginRoute = ConfiguredLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ConfiguredRouteRoute,
} as any)
const ConfiguredAuthenticatedRouteRoute =
  ConfiguredAuthenticatedRouteRouteImport.update({
    id: '/_authenticated',
    getParentRoute: () => ConfiguredRouteRoute,
  } as any)
const ConfiguredAuthenticatedTorrentsRoute =
  ConfiguredAuthenticatedTorrentsRouteImport.update({
    id: '/torrents',
    path: '/torrents',
    getParentRoute: () => ConfiguredAuthenticatedRouteRoute,
  } as any)
const ConfiguredAuthenticatedSettingsRoute =
  ConfiguredAuthenticatedSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ConfiguredAuthenticatedRouteRoute,
  } as any)
const ConfiguredAuthenticatedAccountRoute =
  ConfiguredAuthenticatedAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => ConfiguredAuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/setup': typeof SetupRoute
  '/login': typeof ConfiguredLoginRoute
  '/account': typeof ConfiguredAuthenticatedAccountRoute
  '/settings': typeof ConfiguredAuthenticatedSettingsRoute
  '/torrents': typeof ConfiguredAuthenticatedTorrentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/setup': typeof SetupRoute
  '/login': typeof ConfiguredLoginRoute
  '/account': typeof ConfiguredAuthenticatedAccountRoute
  '/settings': typeof ConfiguredAuthenticatedSettingsRoute
  '/torrents': typeof ConfiguredAuthenticatedTorrentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_configured': typeof ConfiguredRouteRouteWithChildren
  '/setup': typeof SetupRoute
  '/_configured/_authenticated': typeof ConfiguredAuthenticatedRouteRouteWithChildren
  '/_configured/login': typeof ConfiguredLoginRoute
  '/_configured/_authenticated/account': typeof ConfiguredAuthenticatedAccountRoute
  '/_configured/_authenticated/settings': typeof ConfiguredAuthenticatedSettingsRoute
  '/_configured/_authenticated/torrents': typeof ConfiguredAuthenticatedTorrentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/setup' | '/login' | '/account' | '/settings' | '/torrents'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/setup' | '/login' | '/account' | '/settings' | '/torrents'
  id:
    | '__root__'
    | '/'
    | '/_configured'
    | '/setup'
    | '/_configured/_authenticated'
    | '/_configured/login'
    | '/_configured/_authenticated/account'
    | '/_configured/_authenticated/settings'
    | '/_configured/_authenticated/torrents'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguredRouteRoute: typeof ConfiguredRouteRouteWithChildren
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_configured': {
      id: '/_configured'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ConfiguredRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_configured/login': {
      id: '/_configured/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof ConfiguredLoginRouteImport
      parentRoute: typeof ConfiguredRouteRoute
    }
    '/_configured/_authenticated': {
      id: '/_configured/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ConfiguredAuthenticatedRouteRouteImport
      parentRoute: typeof ConfiguredRouteRoute
    }
    '/_configured/_authenticated/torrents': {
      id: '/_configured/_authenticated/torrents'
      path: '/torrents'
      fullPath: '/torrents'
      preLoaderRoute: typeof ConfiguredAuthenticatedTorrentsRouteImport
      parentRoute: typeof ConfiguredAuthenticatedRouteRoute
    }
    '/_configured/_authenticated/settings': {
      id: '/_configured/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ConfiguredAuthenticatedSettingsRouteImport
      parentRoute: typeof ConfiguredAuthenticatedRouteRoute
    }
    '/_configured/_authenticated/account': {
      id: '/_configured/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof ConfiguredAuthenticatedAccountRouteImport
      parentRoute: typeof ConfiguredAuthenticatedRouteRoute
    }
  }
}

interface ConfiguredAuthenticatedRouteRouteChildren {
  ConfiguredAuthenticatedAccountRoute: typeof ConfiguredAuthenticatedAccountRoute
  ConfiguredAuthenticatedSettingsRoute: typeof ConfiguredAuthenticatedSettingsRoute
  ConfiguredAuthenticatedTorrentsRoute: typeof ConfiguredAuthenticatedTorrentsRoute
}

const ConfiguredAuthenticatedRouteRouteChildren: ConfiguredAuthenticatedRouteRouteChildren =
  {
    ConfiguredAuthenticatedAccountRoute: ConfiguredAuthenticatedAccountRoute,
    ConfiguredAuthenticatedSettingsRoute: ConfiguredAuthenticatedSettingsRoute,
    ConfiguredAuthenticatedTorrentsRoute: ConfiguredAuthenticatedTorrentsRoute,
  }

const ConfiguredAuthenticatedRouteRouteWithChildren =
  ConfiguredAuthenticatedRouteRoute._addFileChildren(
    ConfiguredAuthenticatedRouteRouteChildren,
  )

interface ConfiguredRouteRouteChildren {
  ConfiguredAuthenticatedRouteRoute: typeof ConfiguredAuthenticatedRouteRouteWithChildren
  ConfiguredLoginRoute: typeof ConfiguredLoginRoute
}

const ConfiguredRouteRouteChildren: ConfiguredRouteRouteChildren = {
  ConfiguredAuthenticatedRouteRoute:
    ConfiguredAuthenticatedRouteRouteWithChildren,
  ConfiguredLoginRoute: ConfiguredLoginRoute,
}

const ConfiguredRouteRouteWithChildren = ConfiguredRouteRoute._addFileChildren(
  ConfiguredRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguredRouteRoute: ConfiguredRouteRouteWithChildren,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
